name: Get Electron Source Tarball

on:
  workflow_dispatch:
    inputs:
      revision:
        description: "The revision of electron"
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Echo version
        run: echo "${{ github.event.inputs.revision }}"
      - name: Cleanup Spaces
        run: |
          wget https://raw.githubusercontent.com/termux/termux-packages/refs/heads/master/scripts/free-space.sh
          bash free-space.sh
          sudo rm -rf /usr/local/lib/android
      - name: Generate source tarball
        run: |
          wget https://nodejs.org/dist/v22.15.0/node-v22.15.0-linux-x64.tar.xz
          tar xf node-v22.15.0-linux-x64.tar.xz
          export PATH="$PWD/node-v22.15.0-linux-x64:$PATH"
          REVISION="${{ github.event.inputs.revision }}"
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git depot_tools
          export PATH="$PWD/depot_tools:$PATH"
          gclient config --name "src/electron" --unmanaged https://github.com/electron/electron
          gclient sync --with_branch_heads --with_tags --no-history --revision "$REVISION"
          mkdir -p upload
          tar -I zstd --remove-files -cf "./upload/electron-src-$REVISION.tar.zst" src
      - name: Upload tarball file
        uses: actions/upload-artifact@v4
        with:
          name: upload-${{ github.event.inputs.revision }}-${{ github.sha }}
          path: ./upload
